apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../k3s-base
patches:
  - path: console-online.yaml
    target:
      version: v1
      kind: ConfigMap
      name: incident-console-config
      namespace: k8s-incident-agent
  - path: runtime-online.yaml
    target:
      version: v1
      kind: ConfigMap
      name: agent-runtime-config
      namespace: k8s-incident-agent
