apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: k8s-incident-monitoring
spec:
  template:
    metadata:
      annotations:
        k8s-incident-agent.io/config-digest: "sha256:76cea711016a9715c2884a8a9e07ff9effac603a69c01cabb8128090c7086308"
    spec:
      containers:
        - name: prometheus
          volumeMounts:
            - name: scrape
              mountPath: /etc/prometheus/scrape
              readOnly: true
            - name: kubernetes-credentials
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
      volumes:
        - name: scrape
          configMap:
            name: prometheus-scrape-node-metrics
        - name: kubernetes-credentials
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3600
              - configMap:
                  name: kube-root-ca.crt
                  items:
                    - key: ca.crt
                      path: ca.crt
