/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        /** Create Incident */
        post: operations["create_incident_api_v1_incidents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident */
        get: operations["get_incident_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident Events */
        get: operations["get_incident_events_api_v1_incidents__incident_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateIncidentRequest */
        CreateIncidentRequest: {
            /** Scenarioid */
            scenarioId: string;
        };
        /** CreateIncidentResponse */
        CreateIncidentResponse: {
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            incidentStatus: components["schemas"]["IncidentStatus"];
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            runStatus: components["schemas"]["RunStatus"];
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
        };
        /** DiagnosisCompletedEventPayload */
        DiagnosisCompletedEventPayload: {
            /**
             * Diagnosisid
             * Format: uuid
             */
            diagnosisId: string;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Incidentstatus
             * @constant
             */
            incidentStatus: "DIAGNOSED";
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Outcome
             * @constant
             */
            outcome: "diagnosed";
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Runstatus
             * @constant
             */
            runStatus: "COMPLETED";
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
        };
        /** DiagnosisCompletedStreamEvent */
        DiagnosisCompletedStreamEvent: {
            data: components["schemas"]["DiagnosisCompletedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "diagnosis.completed";
            /** Id */
            id: string;
        };
        /** DiagnosisInsufficientEventPayload */
        DiagnosisInsufficientEventPayload: {
            /**
             * Diagnosisid
             * Format: uuid
             */
            diagnosisId: string;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Incidentstatus
             * @constant
             */
            incidentStatus: "INSUFFICIENT_EVIDENCE";
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Outcome
             * @constant
             */
            outcome: "insufficient_evidence";
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Runstatus
             * @constant
             */
            runStatus: "COMPLETED";
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
        };
        /** DiagnosisInsufficientStreamEvent */
        DiagnosisInsufficientStreamEvent: {
            data: components["schemas"]["DiagnosisInsufficientEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "diagnosis.insufficient";
            /** Id */
            id: string;
        };
        /**
         * DiagnosisOutcome
         * @enum {string}
         */
        DiagnosisOutcome: "diagnosed" | "insufficient_evidence";
        /** DiagnosisResponse */
        DiagnosisResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Missinginformation */
            missingInformation: string[];
            outcome: components["schemas"]["DiagnosisOutcome"];
            /** Redacted */
            redacted: boolean;
            /** Rootcauses */
            rootCauses: components["schemas"]["RootCauseResponse"][];
            /** Summary */
            summary: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** EvidenceRecordedEventPayload */
        EvidenceRecordedEventPayload: {
            /**
             * Evidenceid
             * Format: uuid
             */
            evidenceId: string;
            /** Evidencekind */
            evidenceKind: string;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Observedat
             * Format: date-time
             */
            observedAt: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /** Redacted */
            redacted: boolean;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
            /** Toolcallid */
            toolCallId: string;
            /** Toolname */
            toolName: string;
            /** Truncated */
            truncated: boolean;
        };
        /** EvidenceRecordedStreamEvent */
        EvidenceRecordedStreamEvent: {
            data: components["schemas"]["EvidenceRecordedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "evidence.recorded";
            /** Id */
            id: string;
        };
        /** EvidenceResponse */
        EvidenceResponse: {
            /** Evidencekind */
            evidenceKind: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Observedat
             * Format: date-time
             */
            observedAt: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Redacted */
            redacted: boolean;
            /** Targetref */
            targetRef: {
                [key: string]: unknown;
            };
            /** Toolcallid */
            toolCallId: string;
            /** Toolname */
            toolName: string;
            /** Truncated */
            truncated: boolean;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** IncidentCreatedEventPayload */
        IncidentCreatedEventPayload: {
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Incidentstatus
             * @constant
             */
            incidentStatus: "RECEIVED";
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Runstatus
             * @constant
             */
            runStatus: "QUEUED";
            /** Scenarioid */
            scenarioId: string;
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
        };
        /** IncidentCreatedStreamEvent */
        IncidentCreatedStreamEvent: {
            data: components["schemas"]["IncidentCreatedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "incident.created";
            /** Id */
            id: string;
        };
        /** IncidentDetailResponse */
        IncidentDetailResponse: {
            diagnosis: components["schemas"]["DiagnosisResponse"] | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceResponse"][];
            incident: components["schemas"]["IncidentResponse"];
            run: components["schemas"]["RunResponse"];
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
        };
        /** IncidentListItem */
        IncidentListItem: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Displayname */
            displayName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Scenarioid */
            scenarioId: string;
            /** Scenarioversion */
            scenarioVersion: number;
            status: components["schemas"]["IncidentStatus"];
            target: components["schemas"]["ScenarioTargetResponse"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** IncidentListResponse */
        IncidentListResponse: {
            /** Items */
            items: components["schemas"]["IncidentListItem"][];
            /** Nextcursor */
            nextCursor: string | null;
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
        };
        /** IncidentResponse */
        IncidentResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Displayname */
            displayName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Scenarioid */
            scenarioId: string;
            /** Scenarioversion */
            scenarioVersion: number;
            status: components["schemas"]["IncidentStatus"];
            target: components["schemas"]["ScenarioTargetResponse"];
            /** Triggersummary */
            triggerSummary: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * IncidentStatus
         * @enum {string}
         */
        IncidentStatus: "RECEIVED" | "TRIAGING" | "DIAGNOSED" | "INSUFFICIENT_EVIDENCE" | "FAILED";
        /** RootCauseResponse */
        RootCauseResponse: {
            /** Code */
            code: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Evidenceids */
            evidenceIds: string[];
            /** Statement */
            statement: string;
        };
        /** RunBudgetResponse */
        RunBudgetResponse: {
            /** Maxmodelcalls */
            maxModelCalls: number;
            /** Maxtoolcalls */
            maxToolCalls: number;
            /** Timeoutseconds */
            timeoutSeconds: number;
        };
        /** RunErrorResponse */
        RunErrorResponse: {
            /** Code */
            code: string;
            /** Retryable */
            retryable: boolean;
        };
        /** RunEventStreamItem */
        RunEventStreamItem: components["schemas"]["IncidentCreatedStreamEvent"] | components["schemas"]["RunStartedStreamEvent"] | components["schemas"]["ToolStartedStreamEvent"] | components["schemas"]["EvidenceRecordedStreamEvent"] | components["schemas"]["ToolFailedStreamEvent"] | components["schemas"]["DiagnosisCompletedStreamEvent"] | components["schemas"]["DiagnosisInsufficientStreamEvent"] | components["schemas"]["RunFailedStreamEvent"];
        /** RunFailedEventPayload */
        RunFailedEventPayload: {
            /** Errorcode */
            errorCode: string;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Incidentstatus
             * @constant
             */
            incidentStatus: "FAILED";
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /** Retryable */
            retryable: boolean;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Runstatus
             * @constant
             */
            runStatus: "FAILED";
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
        };
        /** RunFailedStreamEvent */
        RunFailedStreamEvent: {
            data: components["schemas"]["RunFailedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "run.failed";
            /** Id */
            id: string;
        };
        /** RunResponse */
        RunResponse: {
            budget: components["schemas"]["RunBudgetResponse"];
            /** Completedat */
            completedAt: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            error: components["schemas"]["RunErrorResponse"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Modelid */
            modelId: string;
            /** Modelprovider */
            modelProvider: string;
            /** Promptversion */
            promptVersion: string;
            /** Startedat */
            startedAt: string | null;
            status: components["schemas"]["RunStatus"];
            /** Thinkingmode */
            thinkingMode: boolean;
            usage: components["schemas"]["RunUsageResponse"];
        };
        /** RunStartedEventPayload */
        RunStartedEventPayload: {
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Incidentstatus
             * @constant
             */
            incidentStatus: "TRIAGING";
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Runstatus
             * @constant
             */
            runStatus: "RUNNING";
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
        };
        /** RunStartedStreamEvent */
        RunStartedStreamEvent: {
            data: components["schemas"]["RunStartedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "run.started";
            /** Id */
            id: string;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED";
        /** RunUsageResponse */
        RunUsageResponse: {
            /** Inputtokens */
            inputTokens: number | null;
            /** Modelcalls */
            modelCalls: number | null;
            /** Outputtokens */
            outputTokens: number | null;
            /** Toolcalls */
            toolCalls: number | null;
        };
        /** ScenarioListResponse */
        ScenarioListResponse: {
            /** Items */
            items: components["schemas"]["ScenarioResponse"][];
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
        };
        /** ScenarioResponse */
        ScenarioResponse: {
            /** Description */
            description: string;
            /** Displayname */
            displayName: string;
            /** Scenarioid */
            scenarioId: string;
            /** Scenarioversion */
            scenarioVersion: number;
            target: components["schemas"]["ScenarioTargetResponse"];
            trigger: components["schemas"]["ScenarioTriggerResponse"];
        };
        /** ScenarioTargetResponse */
        ScenarioTargetResponse: {
            /** Apiversion */
            apiVersion: string;
            /** Cluster */
            cluster: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Namespace */
            namespace: string;
        };
        /** ScenarioTriggerResponse */
        ScenarioTriggerResponse: {
            /** Summary */
            summary: string;
            /**
             * Type
             * @constant
             */
            type: "manual";
        };
        /** ToolFailedEventPayload */
        ToolFailedEventPayload: {
            /** Errorcode */
            errorCode: string;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /** Retryable */
            retryable: boolean;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
            /** Toolcallid */
            toolCallId: string;
            /** Toolname */
            toolName: string;
        };
        /** ToolFailedStreamEvent */
        ToolFailedStreamEvent: {
            data: components["schemas"]["ToolFailedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "tool.failed";
            /** Id */
            id: string;
        };
        /** ToolStartedEventPayload */
        ToolStartedEventPayload: {
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
            /** Toolcallid */
            toolCallId: string;
            /** Toolname */
            toolName: string;
        };
        /** ToolStartedStreamEvent */
        ToolStartedStreamEvent: {
            data: components["schemas"]["ToolStartedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "tool.started";
            /** Id */
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentListResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_incident_api_v1_incidents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIncidentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateIncidentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_incident_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_incident_events_api_v1_incidents__incident_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["RunEventStreamItem"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_scenarios_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioListResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
