/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/alerts/alertmanager": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive Alertmanager Webhook */
        post: operations["receive_alertmanager_webhook_api_v1_alerts_alertmanager_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        /** Create Incident */
        post: operations["create_incident_api_v1_incidents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident */
        get: operations["get_incident_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident Events */
        get: operations["get_incident_events_api_v1_incidents__incident_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/monitoring/panels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incident Monitoring Panels */
        get: operations["list_incident_monitoring_panels_api_v1_incidents__incident_id__monitoring_panels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/monitoring/panels/{panel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident Monitoring Panel */
        get: operations["get_incident_monitoring_panel_api_v1_incidents__incident_id__monitoring_panels__panel_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_incidents__incident_id__runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_incidents__incident_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Run Events */
        get: operations["list_run_events_api_v1_incidents__incident_id__runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Monitoring Health */
        get: operations["get_monitoring_health_api_v1_monitoring_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Monitoring Overview */
        get: operations["get_monitoring_overview_api_v1_monitoring_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertResolvedEventPayload */
        AlertResolvedEventPayload: {
            /**
             * Alertstatus
             * @constant
             */
            alertStatus: "RESOLVED";
            /** Endsat */
            endsAt: string;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 4;
        };
        /** AlertResolvedStreamEvent */
        AlertResolvedStreamEvent: {
            data: components["schemas"]["AlertResolvedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "alert.resolved";
            /** Id */
            id: string;
        };
        /** AlertSignalResponse */
        AlertSignalResponse: {
            /** Endsat */
            endsAt: string | null;
            /** Startsat */
            startsAt: string;
            status: components["schemas"]["AlertSignalStatus"];
        };
        /**
         * AlertSignalStatus
         * @enum {string}
         */
        AlertSignalStatus: "FIRING" | "RESOLVED";
        /** AlertmanagerAlert */
        AlertmanagerAlert: {
            /** Annotations */
            annotations: {
                [key: string]: string;
            };
            /** Endsat */
            endsAt: string;
            /** Fingerprint */
            fingerprint: string;
            /** Generatorurl */
            generatorURL: string;
            /** Labels */
            labels: {
                [key: string]: string;
            };
            /** Startsat */
            startsAt: string;
            /**
             * Status
             * @enum {string}
             */
            status: "firing" | "resolved";
        };
        /** AlertmanagerWebhook */
        AlertmanagerWebhook: {
            /** Alerts */
            alerts: components["schemas"]["AlertmanagerAlert"][];
            /** Commonannotations */
            commonAnnotations: {
                [key: string]: string;
            };
            /** Commonlabels */
            commonLabels: {
                [key: string]: string;
            };
            /** Externalurl */
            externalURL: string;
            /** Groupkey */
            groupKey: string;
            /** Grouplabels */
            groupLabels: {
                [key: string]: string;
            };
            /** Notification Reason */
            notification_reason: string;
            /** Receiver */
            receiver: string;
            /** Routelabels */
            routeLabels: {
                [key: string]: string;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "firing" | "resolved";
            /** Truncatedalerts */
            truncatedAlerts: number;
            /**
             * Version
             * @constant
             */
            version: "4";
        };
        /** CreateIncidentRequest */
        CreateIncidentRequest: {
            /** Scenarioid */
            scenarioId: string;
        };
        /** CreateIncidentResponse */
        CreateIncidentResponse: {
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Schemaversion
             * @default 4
             * @constant
             */
            schemaVersion: 4;
        };
        /** CreateRunResponse */
        CreateRunResponse: {
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Schemaversion
             * @default 4
             * @constant
             */
            schemaVersion: 4;
        };
        /** DiagnosisCompletedEventPayload */
        DiagnosisCompletedEventPayload: {
            /**
             * Diagnosisid
             * Format: uuid
             */
            diagnosisId: string;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Incidentstatus
             * @constant
             */
            incidentStatus: "DIAGNOSED";
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Outcome
             * @constant
             */
            outcome: "diagnosed";
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Runstatus
             * @enum {string}
             */
            runStatus: "RUNNING" | "COMPLETED";
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 4;
        };
        /** DiagnosisCompletedStreamEvent */
        DiagnosisCompletedStreamEvent: {
            data: components["schemas"]["DiagnosisCompletedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "diagnosis.completed";
            /** Id */
            id: string;
        };
        /** DiagnosisInsufficientEventPayload */
        DiagnosisInsufficientEventPayload: {
            /**
             * Diagnosisid
             * Format: uuid
             */
            diagnosisId: string;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Incidentstatus
             * @constant
             */
            incidentStatus: "INSUFFICIENT_EVIDENCE";
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Outcome
             * @constant
             */
            outcome: "insufficient_evidence";
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Runstatus
             * @constant
             */
            runStatus: "COMPLETED";
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 4;
        };
        /** DiagnosisInsufficientStreamEvent */
        DiagnosisInsufficientStreamEvent: {
            data: components["schemas"]["DiagnosisInsufficientEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "diagnosis.insufficient";
            /** Id */
            id: string;
        };
        /**
         * DiagnosisOutcome
         * @enum {string}
         */
        DiagnosisOutcome: "diagnosed" | "insufficient_evidence";
        /** DiagnosisResponse */
        DiagnosisResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Missinginformation */
            missingInformation: string[];
            outcome: components["schemas"]["DiagnosisOutcome"];
            /** Redacted */
            redacted: boolean;
            /** Rootcauses */
            rootCauses: components["schemas"]["RootCauseResponse"][];
            /** Summary */
            summary: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** EventPageResponse */
        EventPageResponse: {
            /** Items */
            items: components["schemas"]["RunEventStreamItem"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /** EvidenceRecordedEventPayload */
        EvidenceRecordedEventPayload: {
            /**
             * Evidenceid
             * Format: uuid
             */
            evidenceId: string;
            /** Evidencekind */
            evidenceKind: string;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Observedat
             * Format: date-time
             */
            observedAt: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /** Redacted */
            redacted: boolean;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 4;
            /** Toolcallid */
            toolCallId: string;
            /** Toolname */
            toolName: string;
            /** Truncated */
            truncated: boolean;
        };
        /** EvidenceRecordedStreamEvent */
        EvidenceRecordedStreamEvent: {
            data: components["schemas"]["EvidenceRecordedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "evidence.recorded";
            /** Id */
            id: string;
        };
        /** EvidenceResponse */
        EvidenceResponse: {
            /** Evidencekind */
            evidenceKind: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Observedat
             * Format: date-time
             */
            observedAt: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Redacted */
            redacted: boolean;
            /** Targetref */
            targetRef: {
                [key: string]: unknown;
            };
            /** Toolcallid */
            toolCallId: string;
            /** Toolname */
            toolName: string;
            /** Truncated */
            truncated: boolean;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** IncidentCreatedEventPayload */
        IncidentCreatedEventPayload: {
            /** Attempt */
            attempt: number;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Incidentstatus
             * @constant
             */
            incidentStatus: "RECEIVED";
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Runstatus
             * @constant
             */
            runStatus: "QUEUED";
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 4;
        };
        /** IncidentCreatedStreamEvent */
        IncidentCreatedStreamEvent: {
            data: components["schemas"]["IncidentCreatedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "incident.created";
            /** Id */
            id: string;
        };
        /** IncidentDetailResponse */
        IncidentDetailResponse: {
            alertSignal: components["schemas"]["AlertSignalResponse"] | null;
            diagnosis: components["schemas"]["DiagnosisResponse"] | null;
            /** Eventcursor */
            eventCursor: string;
            eventPage: components["schemas"]["EventPageResponse"];
            /** Evidence */
            evidence: components["schemas"]["EvidenceResponse"][];
            incident: components["schemas"]["IncidentResponse"];
            repair: components["schemas"]["RepairProposalResponse"] | null;
            /**
             * Schemaversion
             * @default 4
             * @constant
             */
            schemaVersion: 4;
            selectedRun: components["schemas"]["SelectedRunResponse"];
        };
        /** IncidentListItem */
        IncidentListItem: {
            /** Displayname */
            displayName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["IncidentStatus"];
            target: components["schemas"]["IncidentTargetResponse"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** IncidentListResponse */
        IncidentListResponse: {
            /** Items */
            items: components["schemas"]["IncidentListItem"][];
            /** Nextcursor */
            nextCursor: string | null;
            /**
             * Schemaversion
             * @default 4
             * @constant
             */
            schemaVersion: 4;
        };
        /** IncidentMetricPanel */
        IncidentMetricPanel: {
            /** Markers */
            markers: components["schemas"]["MetricMarker"][];
            /** Markerstruncated */
            markersTruncated: boolean;
            result: components["schemas"]["MetricPanelResult"];
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
        };
        /** IncidentMonitoringPanels */
        IncidentMonitoringPanels: {
            /** Panels */
            panels: components["schemas"]["MonitoringPanelReference"][];
            /**
             * Schemaversion
             * @default 3
             * @constant
             */
            schemaVersion: 3;
        };
        /** IncidentResponse */
        IncidentResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Displayname */
            displayName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            source: components["schemas"]["IncidentSourceResponse"];
            status: components["schemas"]["IncidentStatus"];
            target: components["schemas"]["IncidentTargetResponse"];
            /** Triggersummary */
            triggerSummary: string;
        };
        /** IncidentSourceResponse */
        IncidentSourceResponse: {
            /** Ref */
            ref: string;
            /** Revision */
            revision: string;
            /**
             * Type
             * @enum {string}
             */
            type: "scenario" | "alertmanager";
        };
        /**
         * IncidentStatus
         * @enum {string}
         */
        IncidentStatus: "RECEIVED" | "TRIAGING" | "DIAGNOSED" | "PATCH_READY" | "DRY_RUN_PASSED" | "WAITING_APPROVAL" | "INSUFFICIENT_EVIDENCE" | "STALE_RESOURCE" | "FAILED";
        /** IncidentTargetResponse */
        IncidentTargetResponse: {
            /** Apiversion */
            apiVersion: string;
            /** Cluster */
            cluster: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Namespace */
            namespace: string | null;
        };
        /** MetricMarker */
        MetricMarker: {
            kind: components["schemas"]["MetricMarkerKind"];
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /** Runattempt */
            runAttempt?: number | null;
        };
        /**
         * MetricMarkerKind
         * @enum {string}
         */
        MetricMarkerKind: "alert_firing" | "alert_resolved" | "run_started" | "run_completed";
        /** MetricPanelResult */
        MetricPanelResult: {
            /** Currentvalue */
            currentValue: number | null;
            /** Latestsampleat */
            latestSampleAt: string | null;
            /** Panelid */
            panelId: string;
            /**
             * Queriedat
             * Format: date-time
             */
            queriedAt: string;
            riskDirection: components["schemas"]["MetricRiskDirection"];
            /** Samples */
            samples: components["schemas"]["MetricSample"][];
            state: components["schemas"]["MetricQueryState"];
            /** Threshold */
            threshold: number | null;
            /** Title */
            title: string;
            /** Unit */
            unit: string;
            window: components["schemas"]["MetricWindow"];
        };
        /**
         * MetricPanelSignalRole
         * @enum {string}
         */
        MetricPanelSignalRole: "trigger" | "context";
        /**
         * MetricQueryState
         * @enum {string}
         */
        MetricQueryState: "ok" | "no_data" | "stale" | "partial" | "query_error" | "monitoring_unavailable";
        /**
         * MetricRiskDirection
         * @enum {string}
         */
        MetricRiskDirection: "higher_is_worse" | "lower_is_worse";
        /** MetricSample */
        MetricSample: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Value */
            value: number;
        };
        /**
         * MetricWindow
         * @enum {string}
         */
        MetricWindow: "15m" | "1h" | "6h" | "7d" | "15d";
        /**
         * MonitoringComponentState
         * @enum {string}
         */
        MonitoringComponentState: "healthy" | "degraded" | "unavailable" | "stale" | "unknown";
        /** MonitoringHealthSnapshot */
        MonitoringHealthSnapshot: {
            alertmanager: components["schemas"]["MonitoringComponentState"];
            /**
             * Checkedat
             * Format: date-time
             */
            checkedAt: string;
            kubeStateMetrics: components["schemas"]["MonitoringComponentState"];
            notification: components["schemas"]["MonitoringComponentState"];
            prometheus: components["schemas"]["MonitoringComponentState"];
            ruleEvaluation: components["schemas"]["MonitoringComponentState"];
            state: components["schemas"]["MonitoringOverallState"];
            /** Watchdoglastreceivedat */
            watchdogLastReceivedAt: string | null;
        };
        /**
         * MonitoringOverallState
         * @enum {string}
         */
        MonitoringOverallState: "healthy" | "degraded" | "unavailable";
        /** MonitoringOverviewCounts */
        MonitoringOverviewCounts: {
            /** Diagnosedincidents */
            diagnosedIncidents: number;
            /** Firingalerts */
            firingAlerts: number;
            /** Totalincidents */
            totalIncidents: number;
            /** Triagingincidents */
            triagingIncidents: number;
        };
        /** MonitoringOverviewFamily */
        MonitoringOverviewFamily: {
            /** Count */
            count: number;
            /** Displayname */
            displayName: string;
            /** Sourceref */
            sourceRef: string;
        };
        /** MonitoringOverviewSample */
        MonitoringOverviewSample: {
            /** Alertconditionsresolved */
            alertConditionsResolved: number;
            /** Incidentscreated */
            incidentsCreated: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** MonitoringOverviewSnapshot */
        MonitoringOverviewSnapshot: {
            counts: components["schemas"]["MonitoringOverviewCounts"];
            /** Families */
            families: components["schemas"]["MonitoringOverviewFamily"][];
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Samples */
            samples: components["schemas"]["MonitoringOverviewSample"][];
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
            /**
             * Window
             * @default 24h
             * @constant
             */
            window: "24h";
        };
        /** MonitoringPanelReference */
        MonitoringPanelReference: {
            /** Panelid */
            panelId: string;
            recommendedWindow: components["schemas"]["MetricWindow"];
            riskDirection: components["schemas"]["MetricRiskDirection"];
            signalRole: components["schemas"]["MetricPanelSignalRole"];
            /** Thresholdduration */
            thresholdDuration: string | null;
        };
        /** @enum {string} */
        PatchValidationErrorCode: "stale_resource" | "patch_validator_authentication_failed" | "patch_validator_replay_rejected" | "patch_validator_permission_denied" | "patch_validator_admission_denied" | "patch_validator_timeout" | "patch_validator_upstream_failed" | "patch_validator_contract_invalid";
        /** PrometheusToolCallIdentity */
        PrometheusToolCallIdentity: {
            /** Panelid */
            panelId: string;
            /**
             * Window
             * @enum {string}
             */
            window: "15m" | "1h" | "6h" | "7d" | "15d";
        };
        /** RepairDiffResponse */
        RepairDiffResponse: {
            /** After */
            after: string;
            /** Before */
            before: string;
            /** Path */
            path: string;
        };
        /** RepairDryRunPassedEventPayload */
        RepairDryRunPassedEventPayload: {
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Incidentstatus
             * @constant
             */
            incidentStatus: "DRY_RUN_PASSED";
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /** Proposaldigest */
            proposalDigest: string;
            /**
             * Proposalid
             * Format: uuid
             */
            proposalId: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Runstatus
             * @constant
             */
            runStatus: "RUNNING";
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 4;
        };
        /** RepairDryRunPassedStreamEvent */
        RepairDryRunPassedStreamEvent: {
            data: components["schemas"]["RepairDryRunPassedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "repair.dry_run_passed";
            /** Id */
            id: string;
        };
        /** RepairPatchOperationResponse */
        RepairPatchOperationResponse: {
            /**
             * Op
             * @enum {string}
             */
            op: "test" | "replace";
            /** Path */
            path: string;
            /** Value */
            value: string;
        };
        /** RepairPatchReadyEventPayload */
        RepairPatchReadyEventPayload: {
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Incidentstatus
             * @constant
             */
            incidentStatus: "PATCH_READY";
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /** Proposaldigest */
            proposalDigest: string;
            /**
             * Proposalid
             * Format: uuid
             */
            proposalId: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Runstatus
             * @constant
             */
            runStatus: "RUNNING";
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 4;
        };
        /** RepairPatchReadyStreamEvent */
        RepairPatchReadyStreamEvent: {
            data: components["schemas"]["RepairPatchReadyEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "repair.patch_ready";
            /** Id */
            id: string;
        };
        /** RepairProposalResponse */
        RepairProposalResponse: {
            /**
             * Action
             * @constant
             */
            action: "set_container_image";
            /** Containerindex */
            containerIndex: number;
            /** Containername */
            containerName: string;
            /** Currentimage */
            currentImage: string;
            diff: components["schemas"]["RepairDiffResponse"];
            /**
             * Diffcheckedat
             * Format: date-time
             */
            diffCheckedAt: string;
            /** Digest */
            digest: string;
            /** Evidenceids */
            evidenceIds: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Patch */
            patch: components["schemas"]["RepairPatchOperationResponse"][];
            /**
             * Policycheckedat
             * Format: date-time
             */
            policyCheckedAt: string;
            /** Replacementimage */
            replacementImage: string;
            /**
             * Schemacheckedat
             * Format: date-time
             */
            schemaCheckedAt: string;
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
            target: components["schemas"]["IncidentTargetResponse"];
            /** Targetresourceversion */
            targetResourceVersion: string;
            /** Targetuid */
            targetUid: string;
            validation: components["schemas"]["RepairValidationResponse"];
        };
        /** RepairValidationErrorResponse */
        RepairValidationErrorResponse: {
            code: components["schemas"]["PatchValidationErrorCode"];
            /** Retryable */
            retryable: boolean;
        };
        /** RepairValidationResponse */
        RepairValidationResponse: {
            /**
             * Checkedat
             * Format: date-time
             */
            checkedAt: string;
            error: components["schemas"]["RepairValidationErrorResponse"] | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "passed" | "failed";
        };
        /** RepairWaitingApprovalEventPayload */
        RepairWaitingApprovalEventPayload: {
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Incidentstatus
             * @constant
             */
            incidentStatus: "WAITING_APPROVAL";
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /** Proposaldigest */
            proposalDigest: string;
            /**
             * Proposalid
             * Format: uuid
             */
            proposalId: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Runstatus
             * @constant
             */
            runStatus: "COMPLETED";
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 4;
        };
        /** RepairWaitingApprovalStreamEvent */
        RepairWaitingApprovalStreamEvent: {
            data: components["schemas"]["RepairWaitingApprovalEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "repair.waiting_approval";
            /** Id */
            id: string;
        };
        /** RootCauseResponse */
        RootCauseResponse: {
            /** Code */
            code: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Evidenceids */
            evidenceIds: string[];
            /** Statement */
            statement: string;
        };
        /** RunErrorResponse */
        RunErrorResponse: {
            /** Code */
            code: string;
            /** Retryable */
            retryable: boolean;
        };
        /** RunEventHistoryResponse */
        RunEventHistoryResponse: {
            /** Items */
            items: components["schemas"]["RunEventStreamItem"][];
            /** Nextcursor */
            nextCursor: string | null;
            /**
             * Schemaversion
             * @default 4
             * @constant
             */
            schemaVersion: 4;
        };
        /** RunEventStreamItem */
        RunEventStreamItem: components["schemas"]["IncidentCreatedStreamEvent"] | components["schemas"]["RunQueuedStreamEvent"] | components["schemas"]["RunStartedStreamEvent"] | components["schemas"]["ToolStartedStreamEvent"] | components["schemas"]["EvidenceRecordedStreamEvent"] | components["schemas"]["ToolFailedStreamEvent"] | components["schemas"]["DiagnosisCompletedStreamEvent"] | components["schemas"]["DiagnosisInsufficientStreamEvent"] | components["schemas"]["RunFailedStreamEvent"] | components["schemas"]["RepairPatchReadyStreamEvent"] | components["schemas"]["RepairDryRunPassedStreamEvent"] | components["schemas"]["RepairWaitingApprovalStreamEvent"] | components["schemas"]["AlertResolvedStreamEvent"];
        /** RunFailedEventPayload */
        RunFailedEventPayload: {
            /** Errorcode */
            errorCode: string;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Incidentstatus
             * @enum {string}
             */
            incidentStatus: "FAILED" | "STALE_RESOURCE";
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /** Retryable */
            retryable: boolean;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Runstatus
             * @constant
             */
            runStatus: "FAILED";
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 4;
        };
        /** RunFailedStreamEvent */
        RunFailedStreamEvent: {
            data: components["schemas"]["RunFailedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "run.failed";
            /** Id */
            id: string;
        };
        /** RunHistoryResponse */
        RunHistoryResponse: {
            /** Items */
            items: components["schemas"]["RunSummaryResponse"][];
            /** Nextcursor */
            nextCursor: string | null;
            /**
             * Schemaversion
             * @default 4
             * @constant
             */
            schemaVersion: 4;
        };
        /** RunQueuedEventPayload */
        RunQueuedEventPayload: {
            /** Attempt */
            attempt: number;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Runstatus
             * @constant
             */
            runStatus: "QUEUED";
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 4;
        };
        /** RunQueuedStreamEvent */
        RunQueuedStreamEvent: {
            data: components["schemas"]["RunQueuedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "run.queued";
            /** Id */
            id: string;
        };
        /** RunStartedEventPayload */
        RunStartedEventPayload: {
            /** Attempt */
            attempt: number;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Incidentstatus
             * @constant
             */
            incidentStatus: "TRIAGING";
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Runstatus
             * @constant
             */
            runStatus: "RUNNING";
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 4;
        };
        /** RunStartedStreamEvent */
        RunStartedStreamEvent: {
            data: components["schemas"]["RunStartedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "run.started";
            /** Id */
            id: string;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED";
        /** RunSummaryResponse */
        RunSummaryResponse: {
            /** Attempt */
            attempt: number;
            /** Completedat */
            completedAt: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Startedat */
            startedAt: string | null;
            status: components["schemas"]["RunStatus"];
        };
        /** ScenarioListResponse */
        ScenarioListResponse: {
            /** Items */
            items: components["schemas"]["ScenarioResponse"][];
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
        };
        /** ScenarioResponse */
        ScenarioResponse: {
            /** Description */
            description: string;
            /** Displayname */
            displayName: string;
            /** Scenarioid */
            scenarioId: string;
            /** Scenarioversion */
            scenarioVersion: number;
            target: components["schemas"]["ScenarioTargetResponse"];
            trigger: components["schemas"]["ScenarioTriggerResponse"];
        };
        /** ScenarioTargetResponse */
        ScenarioTargetResponse: {
            /** Apiversion */
            apiVersion: string;
            /** Cluster */
            cluster: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Namespace */
            namespace: string;
        };
        /** ScenarioTriggerResponse */
        ScenarioTriggerResponse: {
            /** Summary */
            summary: string;
            /**
             * Type
             * @constant
             */
            type: "manual";
        };
        /** SelectedRunResponse */
        SelectedRunResponse: {
            /** Attempt */
            attempt: number;
            /** Completedat */
            completedAt: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            error: components["schemas"]["RunErrorResponse"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Startedat */
            startedAt: string | null;
            status: components["schemas"]["RunStatus"];
        };
        /** ToolFailedEventPayload */
        ToolFailedEventPayload: {
            /** Errorcode */
            errorCode: string;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /** Retryable */
            retryable: boolean;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 4;
            /** Toolcallid */
            toolCallId: string;
            /** Toolname */
            toolName: string;
        };
        /** ToolFailedStreamEvent */
        ToolFailedStreamEvent: {
            data: components["schemas"]["ToolFailedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "tool.failed";
            /** Id */
            id: string;
        };
        /** ToolStartedEventPayload */
        ToolStartedEventPayload: {
            callIdentity?: components["schemas"]["PrometheusToolCallIdentity"] | null;
            /**
             * Incidentid
             * Format: uuid
             */
            incidentId: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /**
             * Runid
             * Format: uuid
             */
            runId: string;
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 4;
            /** Toolcallid */
            toolCallId: string;
            /** Toolname */
            toolName: string;
        };
        /** ToolStartedStreamEvent */
        ToolStartedStreamEvent: {
            data: components["schemas"]["ToolStartedEventPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "tool.started";
            /** Id */
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    receive_alertmanager_webhook_api_v1_alerts_alertmanager_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertmanagerWebhook"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentListResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_incident_api_v1_incidents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIncidentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateIncidentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_incident_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: {
                runId?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_incident_events_api_v1_incidents__incident_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["RunEventStreamItem"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_incident_monitoring_panels_api_v1_incidents__incident_id__monitoring_panels_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentMonitoringPanels"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_incident_monitoring_panel_api_v1_incidents__incident_id__monitoring_panels__panel_id__get: {
        parameters: {
            query?: {
                window?: components["schemas"]["MetricWindow"];
            };
            header?: never;
            path: {
                incident_id: string;
                panel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentMetricPanel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_runs_api_v1_incidents__incident_id__runs_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunHistoryResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_run_api_v1_incidents__incident_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_run_events_api_v1_incidents__incident_id__runs__run_id__events_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                incident_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventHistoryResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_monitoring_health_api_v1_monitoring_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitoringHealthSnapshot"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_monitoring_overview_api_v1_monitoring_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitoringOverviewSnapshot"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_scenarios_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioListResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
