apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../platform/k3s
patches:
  - path: runtime-data.yaml
    target:
      version: v1
      kind: PersistentVolumeClaim
      name: runtime-data
      namespace: k8s-incident-agent
