apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runtime-data
  namespace: k8s-incident-agent
  labels:
    app.kubernetes.io/name: agent-runtime
    app.kubernetes.io/part-of: k8s-incident-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
