apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../platform/kind-storage
patches:
  - path: runtime-data.yaml
    target:
      version: v1
      kind: PersistentVolumeClaim
      name: runtime-data
      namespace: k8s-incident-agent
  - path: runtime-volume-permissions.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: agent-runtime
      namespace: k8s-incident-agent
