apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runtime-data
  namespace: k8s-incident-agent
spec:
  storageClassName: k8s-incident-agent-kind
  volumeName: k8s-incident-agent-runtime-data
