apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: k8s-incident-monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: k8s-incident-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
