apiVersion: v1
kind: Service
metadata:
  name: service-selector-mismatch
  namespace: k8s-incident-scenarios
  labels:
    k8s-incident-agent.io/monitor-selector: "true"
spec:
  type: ClusterIP
  selector:
    app: service-selector-wrong
  ports:
    - name: http
      port: 80
      targetPort: 8080
