apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-accounts.yaml
  - diagnostic-rbac.yaml
  - config-maps.yaml
  - services.yaml
  - deployments.yaml
  - network-policies.yaml
images:
  - name: k8s-incident-agent-console
    newName: k8s-incident-agent-console
    digest: sha256:4db61a8e596593ee73f55e24afa631873c7675419cfc7a5ec41b6d0c45817a86
  - name: k8s-incident-agent-runtime
    newName: k8s-incident-agent-runtime
    digest: sha256:440bd91ec5f7e346c826b548232870b8c1a72394aaebbc2103b423afd57dedc7
