apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-accounts.yaml
  - diagnostic-rbac.yaml
  - patch-validator-rbac.yaml
  - patch-validator-admission.yaml
  - config-maps.yaml
  - services.yaml
  - deployments.yaml
  - network-policies.yaml
images:
  - name: k8s-incident-agent-console
    newName: k8s-incident-agent-console
    digest: sha256:d4b0c1bdb87e1ae2b2718da86d88303e5318de08789b0e9444971d009a34a5a7
  - name: k8s-incident-agent-runtime
    newName: k8s-incident-agent-runtime
    digest: sha256:c48d4f8bad354a72e7cd3b64cb365321ba910c1d3452cdd9152d11926eb708cb
