apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-accounts.yaml
  - diagnostic-rbac.yaml
  - patch-validator-rbac.yaml
  - patch-validator-admission.yaml
  - config-maps.yaml
  - services.yaml
  - deployments.yaml
  - network-policies.yaml
images:
  - name: k8s-incident-agent-console
    newName: k8s-incident-agent-console
    digest: sha256:2b941bd920c6897314c5e420c9048d5c360a27429145ce94d06d18b14d0c9815
  - name: k8s-incident-agent-runtime
    newName: k8s-incident-agent-runtime
    digest: sha256:b38aaba4e14d8593526b0666da40e53080238f0d8c9ff854b073d524cfd2f1eb
