apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../platform/kind-storage
patches:
  - path: prometheus-data.yaml
    target:
      version: v1
      kind: PersistentVolumeClaim
      name: prometheus-data
      namespace: k8s-incident-monitoring
  - path: prometheus-volume-permissions.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: prometheus
      namespace: k8s-incident-monitoring
images:
  - name: k8s-incident-agent-runtime
    newName: k8s-incident-agent-runtime
    digest: sha256:3df7b8cf53eb4f4eec2dd8b397be667ebf5ea2c6584c1999cc2d3b96f1dad961
