apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../platform/kind-storage
patches:
  - path: prometheus-data.yaml
    target:
      version: v1
      kind: PersistentVolumeClaim
      name: prometheus-data
      namespace: k8s-incident-monitoring
  - path: prometheus-volume-permissions.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: prometheus
      namespace: k8s-incident-monitoring
images:
  - name: k8s-incident-agent-runtime
    newName: k8s-incident-agent-runtime
    digest: sha256:2b88637f97495bf9d7becb59af4c359e7ad4e49c30b896a8aab3ff132c5b311c
