apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../platform/kind-storage
patches:
  - path: prometheus-data.yaml
    target:
      version: v1
      kind: PersistentVolumeClaim
      name: prometheus-data
      namespace: k8s-incident-monitoring
  - path: prometheus-volume-permissions.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: prometheus
      namespace: k8s-incident-monitoring
images:
  - name: k8s-incident-agent-runtime
    newName: k8s-incident-agent-runtime
    digest: sha256:b38aaba4e14d8593526b0666da40e53080238f0d8c9ff854b073d524cfd2f1eb
