apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage-class-missing
  namespace: k8s-incident-scenarios
  labels:
    k8s-incident-agent.io/pending-policy: immediate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pvc-storage-class-missing-absent
  resources:
    requests:
      storage: 1Mi
