apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-incident-agent-prometheus-data
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: k8s-incident-agent
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: k8s-incident-agent-monitoring-kind
  volumeMode: Filesystem
  hostPath:
    path: /var/local/k8s-incident-monitoring
    type: DirectoryOrCreate
